### PR TITLE
added an fh database generator

### PR DESCRIPTION
**Pull request by fredkingham**

### CODE REVIEW

**Comment by fredkingham** [comment]
killed it

**Comment by davidmiller** [comment]
@fredkingham Do we actually want to merge this into 0.1 ? 

Have we figured out what we're doing WRT UCH/RFH splits in Gloss ?
If those end up being separate repostitories or in the relevant elCID@X repo then maybe this doesn't end up living here?

**Comment by fredkingham** [comment]
That's a good shout, the plan is to just install gloss and have seperate repos for uch and rfh which is pretty much all set to go now since the last gloss refactor.

**Comment by davidmiller** [comment]
If you think we don't need to test the database generator I could probably be convinced, but we should definitely add it to `.coveragerc` ... :)

**Comment by fredkingham** [comment]
updated the coveragerc

**Comment by davidmiller** [comment]
@fredkingham Don't suppose we can kill `gloss/importers/import_message.py` as part of this ?

**Pull request merged**
